// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getBlocked = `-- name: GetBlocked :one
SELECT room_id, uid, nickname, created_at FROM blocked
WHERE room_id = $1 AND uid = $2
`

type GetBlockedParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Uid    string    `json:"uid"`
}

func (q *Queries) GetBlocked(ctx context.Context, arg GetBlockedParams) (Blocked, error) {
	row := q.db.QueryRow(ctx, getBlocked, arg.RoomID, arg.Uid)
	var i Blocked
	err := row.Scan(
		&i.RoomID,
		&i.Uid,
		&i.Nickname,
		&i.CreatedAt,
	)
	return i, err
}
