// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countChannelsByRoom = `-- name: CountChannelsByRoom :one
SELECT COUNT(*)::bigint FROM channels
WHERE room_id = $1
`

func (q *Queries) CountChannelsByRoom(ctx context.Context, roomID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsByRoom, roomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (room_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, room_id, name, created_at, description
`

type CreateChannelParams struct {
	RoomID      uuid.UUID `json:"room_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.RoomID, arg.Name, arg.Description)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE id = $1 AND room_id = $2
`

type DeleteChannelParams struct {
	ID     uuid.UUID `json:"id"`
	RoomID uuid.UUID `json:"room_id"`
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) error {
	_, err := q.db.Exec(ctx, deleteChannel, arg.ID, arg.RoomID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, room_id, name, created_at, description FROM channels
WHERE id = $1 AND room_id = $2
`

type GetChannelParams struct {
	ID     uuid.UUID `json:"id"`
	RoomID uuid.UUID `json:"room_id"`
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, arg.ID, arg.RoomID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const listChannelsByRoom = `-- name: ListChannelsByRoom :many
SELECT id, room_id, name, created_at, description FROM channels
WHERE room_id = $1
ORDER BY created_at
`

func (q *Queries) ListChannelsByRoom(ctx context.Context, roomID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Name,
			&i.CreatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $3, description = $4
WHERE id = $1 AND room_id = $2
RETURNING id, room_id, name, created_at, description
`

type UpdateChannelParams struct {
	ID          uuid.UUID `json:"id"`
	RoomID      uuid.UUID `json:"room_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.RoomID,
		arg.Name,
		arg.Description,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Name,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}
