// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (room_id, uid, nickname, role)
VALUES ($1, $2, $3, $4)
RETURNING room_id, uid, nickname, role, created_at
`

type CreateMemberParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	Uid      string    `json:"uid"`
	Nickname string    `json:"nickname"`
	Role     string    `json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.RoomID,
		arg.Uid,
		arg.Nickname,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.RoomID,
		&i.Uid,
		&i.Nickname,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT room_id, uid, nickname, role, created_at FROM members
WHERE room_id = $1 AND uid = $2
`

type GetMemberParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Uid    string    `json:"uid"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, arg.RoomID, arg.Uid)
	var i Member
	err := row.Scan(
		&i.RoomID,
		&i.Uid,
		&i.Nickname,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembersByRoom = `-- name: ListMembersByRoom :many
SELECT room_id, uid, nickname, role, created_at FROM members
WHERE room_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembersByRoom(ctx context.Context, roomID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembersByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.RoomID,
			&i.Uid,
			&i.Nickname,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberRole = `-- name: SetMemberRole :one
UPDATE members
SET role = $3
WHERE room_id = $1 AND uid = $2 AND role <> 'owner'
RETURNING room_id, uid, nickname, role, created_at
`

type SetMemberRoleParams struct {
	RoomID uuid.UUID `json:"room_id"`
	Uid    string    `json:"uid"`
	Role   string    `json:"role"`
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, setMemberRole, arg.RoomID, arg.Uid, arg.Role)
	var i Member
	err := row.Scan(
		&i.RoomID,
		&i.Uid,
		&i.Nickname,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
