// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        uuid.UUID          `json:"id"`
	RoomID    uuid.UUID          `json:"room_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Member struct {
	RoomID    uuid.UUID          `json:"room_id"`
	Uid       string             `json:"uid"`
	Nickname  string             `json:"nickname"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	OwnerUid  string             `json:"owner_uid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
