// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, code, owner_uid)
VALUES ($1, $2, $3)
RETURNING id, name, code, owner_uid, created_at
`

type CreateRoomParams struct {
	Name     string `json:"name"`
	Code     string `json:"code"`
	OwnerUid string `json:"owner_uid"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.Code, arg.OwnerUid)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.OwnerUid,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT id, name, code, owner_uid, created_at FROM rooms
WHERE code = $1
`

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.OwnerUid,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, code, owner_uid, created_at FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.OwnerUid,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoomName = `-- name: UpdateRoomName :one
UPDATE rooms
SET name = $2
WHERE id = $1
RETURNING id, name, code, owner_uid, created_at
`

type UpdateRoomNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomName, arg.ID, arg.Name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.OwnerUid,
		&i.CreatedAt,
	)
	return i, err
}
