// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (uid, nickname, recovery_code_hash)
VALUES ($1, $2, $3)
RETURNING uid, nickname, recovery_code_hash, created_at
`

type CreateUserParams struct {
	Uid              string `json:"uid"`
	Nickname         string `json:"nickname"`
	RecoveryCodeHash string `json:"recovery_code_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Uid, arg.Nickname, arg.RecoveryCodeHash)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Nickname,
		&i.RecoveryCodeHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByRecoveryHash = `-- name: GetUserByRecoveryHash :one
SELECT uid, nickname, recovery_code_hash, created_at FROM users
WHERE recovery_code_hash = $1
`

func (q *Queries) GetUserByRecoveryHash(ctx context.Context, recoveryCodeHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRecoveryHash, recoveryCodeHash)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Nickname,
		&i.RecoveryCodeHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUID = `-- name: GetUserByUID :one
SELECT uid, nickname, recovery_code_hash, created_at FROM users
WHERE uid = $1
`

func (q *Queries) GetUserByUID(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUID, uid)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Nickname,
		&i.RecoveryCodeHash,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomsByMemberUID = `-- name: ListRoomsByMemberUID :many
SELECT r.id, r.name, r.code, m.role
FROM members m
INNER JOIN rooms r ON r.id = m.room_id
WHERE m.uid = $1
ORDER BY m.created_at DESC
`

type ListRoomsByMemberUIDRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Code string    `json:"code"`
	Role string    `json:"role"`
}

func (q *Queries) ListRoomsByMemberUID(ctx context.Context, uid string) ([]ListRoomsByMemberUIDRow, error) {
	rows, err := q.db.Query(ctx, listRoomsByMemberUID, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsByMemberUIDRow
	for rows.Next() {
		var i ListRoomsByMemberUIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserNickname = `-- name: UpdateUserNickname :one
UPDATE users
SET nickname = $2
WHERE uid = $1
RETURNING uid, nickname, recovery_code_hash, created_at
`

type UpdateUserNicknameParams struct {
	Uid      string `json:"uid"`
	Nickname string `json:"nickname"`
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserNickname, arg.Uid, arg.Nickname)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Nickname,
		&i.RecoveryCodeHash,
		&i.CreatedAt,
	)
	return i, err
}
